name: Build AzerothCore for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencias
      run: |
        choco install cmake git ninja python mariadb vcredist140 -y
        
        # Instalar Boost 1.78.0 específicamente
        $boostDir = "C:\local\boost_1_78_0"
        New-Item -ItemType Directory -Force -Path $boostDir | Out-Null
        
        # Descargar Boost 1.78.0
        $boostUrl = "https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.zip"
        $boostZip = "$env:TEMP\boost_1_78_0.zip"
        Invoke-WebRequest -Uri $boostUrl -OutFile $boostZip
        
        # Extraer Boost
        Expand-Archive -Path $boostZip -DestinationPath "C:\local" -Force
        
        # Compilar Boost
        cd $boostDir
        .\bootstrap.bat
        .\b2.exe toolset=msvc-14.0 address-model=64 architecture=x86 link=static runtime-link=static threading=multi --build-type=complete --with-system --with-filesystem --with-program_options --with-iostreams --with-regex --prefix=$boostDir install
        
        # Copiar archivos de configuración
        $configDir = "$boostDir\lib\cmake\Boost-1.78.0"
        New-Item -ItemType Directory -Force -Path $configDir | Out-Null
        Copy-Item "$pwd\deps\boost_config\*" -Destination $configDir -Force
        
        echo "BOOST_ROOT=$boostDir" >> $env:GITHUB_ENV
        echo "BOOST_LIBRARYDIR=$boostDir\lib" >> $env:GITHUB_ENV
        echo "BOOST_DIR=$boostDir\lib\cmake\Boost-1.78.0" >> $env:GITHUB_ENV

    - name: Configurando CMake
      run: |
        # Actualizar políticas de CMake para evitar warnings
        cmake -S . -B build -G "Ninja" `
          -DCMAKE_POLICY_DEFAULT_CMP0144=NEW `
          -DCMAKE_POLICY_DEFAULT_CMP0167=NEW `
          -DWITH_ELUNA=ON `
          -DCMAKE_BUILD_TYPE=Release `
          -DBOOST_ROOT="$env:BOOST_ROOT" `
          -DBoost_LIBRARY_DIR="$env:BOOST_LIBRARYDIR" `
          -DBoost_DIR="$env:BOOST_DIR" `
          -DBoost_NO_SYSTEM_PATHS=ON `
          -DBoost_USE_STATIC_LIBS=ON `
          -DBoost_DEBUG=ON `
          -DBOOST_ALL_DYN_LINK=OFF `
          -DBoost_ARCHITECTURE="-x64"

    - name: Build AzerothCore
      run: cmake --build build --parallel 4