name: Build AzerothCore for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Show checkout progress
      run: |
        Write-Host "Obteniendo repositorio..." -NoNewline
        $progress = 0
        $total = 100
        while ($progress -lt $total) {
            $progress += 1
            Write-Host "`rObteniendo repositorio... $progress%" -NoNewline
            Start-Sleep -Milliseconds 20
        }
        Write-Host "`rObteniendo repositorio... 100% ✓"

    - name: Install dependencias
      run: |
        choco install cmake git ninja python mariadb vcredist140 boost-msvc-14.3 -y
        # Detectar ruta de Boost instalada por Chocolatey
        $boostDir = Get-ChildItem "C:\local\boost_*" | Select-Object -First 1 -ExpandProperty FullName
        if (-not $boostDir) { throw "No se encontró la instalación de Boost" }
        
        # Copiar archivos de configuración
        $configDir = "$boostDir\lib\cmake\Boost-1.78.0"
        New-Item -ItemType Directory -Force -Path $configDir | Out-Null
        Copy-Item "$pwd\deps\boost_config\*" -Destination $configDir -Force
        
        echo "BOOST_ROOT=$boostDir" >> $env:GITHUB_ENV
        echo "BOOST_LIBRARYDIR=$boostDir\lib64-msvc-14.3" >> $env:GITHUB_ENV
        echo "BOOST_DIR=$boostDir\lib\cmake\Boost-1.78.0" >> $env:GITHUB_ENV

    - name: Configurando CMake
      run: |
        # Actualizar políticas de CMake para evitar warnings
        cmake -S . -B build -G "Ninja" `
          -DCMAKE_POLICY_DEFAULT_CMP0144=NEW `
          -DCMAKE_POLICY_DEFAULT_CMP0167=NEW `
          -DWITH_ELUNA=ON `
          -DCMAKE_BUILD_TYPE=Release `
          -DBOOST_ROOT="$env:BOOST_ROOT" `
          -DBoost_LIBRARY_DIR="$env:BOOST_LIBRARYDIR" `
          -DBoost_DIR="$env:BOOST_DIR" `
          -DBoost_NO_SYSTEM_PATHS=ON `
          -DBoost_USE_STATIC_LIBS=ON `
          -DBoost_DEBUG=ON `
          -DBOOST_ALL_DYN_LINK=OFF `
          -DBoost_ARCHITECTURE="-x64"

    - name: Build AzerothCore
      run: cmake --build build --parallel 4